services:
  estoque:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - ESTOQUE_DATASOURCE_URL=postgresql
      - ESTOQUE_DATASOURCE_PORT=5432
      - ESTOQUE_DATASOURCE_USERNAME=postgres
      - ESTOQUE_DATASOURCE_PASSWORD=postgres
    networks:
      - springboot-postgres-network

  postgresql:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=estoque
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - springboot-postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 10
      interval: 10s
      timeout: 5s

volumes:
  postgres-data:

networks:
  springboot-postgres-network:
    name: fiap-network
