### Criar estoque

POST http://localhost:8084/estoques
Content-Type: application/json

{
  "idProduto": 1,
  "quantidade": 30
}

### Consultar estoque

GET http://localhost:8084/estoques/1
Accept: application/json

### Baixar estoque (lista de produtos)


POST http://localhost:8084/estoques/baixa
Content-Type: application/json

[
  {
    "idProduto": 1,
    "quantidade": 10
  }
]

### Estornar estoque (quantidade negativa)

POST http://localhost:8084/estoques/baixa
Content-Type: application/json

[
  {
    "idProduto": 1,
    "quantidade": -5
  }
]
